/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _Migrations {
  appliedAt: Generated<Timestamp>;
  name: string;
}

export interface Admins {
  backupCodes: Generated<Json>;
  createdAt: Generated<Timestamp>;
  email: string;
  emailOtpEnabled: Generated<boolean>;
  id: string;
  inviteConsumedAt: Timestamp | null;
  inviteExpiresAt: Timestamp | null;
  inviteTokenHash: string | null;
  language: Generated<string>;
  locale: Generated<string>;
  name: string;
  passwordHash: string | null;
  totpIv: Buffer | null;
  totpSecretEnc: Buffer | null;
  totpTag: Buffer | null;
  webauthnCreds: Generated<Json>;
}

export interface AuditLog {
  action: string;
  actorId: string | null;
  actorType: string;
  id: string;
  ip: string | null;
  metadata: Generated<Json>;
  targetId: string | null;
  targetType: string | null;
  ts: Generated<Timestamp>;
  userAgentHash: string | null;
  visibleToCustomer: Generated<boolean>;
}

export interface CredentialRequests {
  createdAt: Generated<Timestamp>;
  customerId: string;
  fields: Generated<Json>;
  fulfilledCredentialId: string | null;
  id: string;
  notApplicableReason: string | null;
  provider: string;
  requestedByAdminId: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Credentials {
  createdAt: Generated<Timestamp>;
  createdBy: string;
  customerId: string;
  id: string;
  label: string;
  needsUpdate: Generated<boolean>;
  payloadCiphertext: Buffer;
  payloadIv: Buffer;
  payloadTag: Buffer;
  provider: string;
  updatedAt: Generated<Timestamp>;
}

export interface Customers {
  createdAt: Generated<Timestamp>;
  dekCiphertext: Buffer;
  dekIv: Buffer;
  dekTag: Buffer;
  domicilio: string | null;
  id: string;
  nif: string | null;
  razonSocial: string;
  representanteCargo: string | null;
  representanteDni: string | null;
  representanteNombre: string | null;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface CustomerUsers {
  backupCodes: Generated<Json>;
  createdAt: Generated<Timestamp>;
  customerId: string;
  email: string;
  emailOtpEnabled: Generated<boolean>;
  id: string;
  inviteConsumedAt: Timestamp | null;
  inviteExpiresAt: Timestamp | null;
  inviteTokenHash: string | null;
  language: Generated<string>;
  locale: Generated<string>;
  name: string;
  passwordHash: string | null;
  totpIv: Buffer | null;
  totpSecretEnc: Buffer | null;
  totpTag: Buffer | null;
  webauthnCreds: Generated<Json>;
}

export interface DigestSchedules {
  dueAt: Timestamp;
  oldestItemAt: Timestamp;
  recipientId: string;
  recipientType: string;
}

export interface Documents {
  category: string;
  customerId: string;
  id: string;
  mimeType: string;
  originalFilename: string;
  parentId: string | null;
  projectId: string | null;
  sha256: string;
  sizeBytes: Int8;
  storagePath: string;
  uploadedAt: Generated<Timestamp>;
  uploadedByAdminId: string | null;
}

export interface DownloadTokenConsumptions {
  consumedAt: Generated<Timestamp>;
  documentId: string;
  expiresAt: Timestamp;
  tokenHash: string;
}

export interface EmailChangeRequests {
  cancelledAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: string;
  newEmail: string;
  oldEmail: string;
  revertedAt: Timestamp | null;
  revertExpiresAt: Timestamp | null;
  revertTokenHash: string | null;
  userId: string;
  userType: string;
  verifiedAt: Timestamp | null;
  verifyExpiresAt: Timestamp;
  verifyTokenHash: string | null;
}

export interface EmailOtpCodes {
  attempts: Generated<number>;
  codeHash: string;
  consumedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  userId: string;
  userType: string;
}

export interface EmailOutbox {
  attempts: Generated<number>;
  createdAt: Generated<Timestamp>;
  id: string;
  idempotencyKey: string;
  lastError: string | null;
  locale: Generated<string>;
  locals: Generated<Json>;
  sendAfter: Generated<Timestamp>;
  sentAt: Timestamp | null;
  status: Generated<string>;
  template: string;
  toAddress: string;
}

export interface InvoicePayments {
  amountCents: number;
  createdAt: Generated<Timestamp>;
  currency: string;
  id: string;
  invoiceId: string;
  note: string | null;
  paidOn: Timestamp;
  recordedBy: string;
}

export interface Invoices {
  amountCents: Int8;
  createdAt: Generated<Timestamp>;
  currency: Generated<string>;
  customerId: string;
  documentId: string;
  dueOn: Timestamp;
  id: string;
  invoiceNumber: string;
  issuedOn: Timestamp;
  notes: string | null;
  status: Generated<string>;
}

export interface Ndas {
  auditDocumentId: string | null;
  customerId: string;
  draftDocumentId: string;
  generatedAt: Generated<Timestamp>;
  generatedByAdminId: string;
  id: string;
  projectId: string;
  signedDocumentId: string | null;
  templateVersionSha: string;
}

export interface PendingDigestItems {
  bucket: string;
  createdAt: Generated<Timestamp>;
  customerId: string | null;
  detail: string | null;
  eventType: string;
  id: string;
  linkPath: string | null;
  metadata: Generated<Json>;
  recipientId: string;
  recipientType: string;
  title: string;
}

export interface Projects {
  createdAt: Generated<Timestamp>;
  customerId: string;
  id: string;
  name: string;
  objetoProyecto: string;
  status: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface ProviderCatalogue {
  active: Generated<boolean>;
  defaultFields: Generated<Json>;
  displayName: string;
  slug: string;
}

export interface RateLimitBuckets {
  count: Generated<number>;
  key: string;
  lockedUntil: Timestamp | null;
  resetAt: Timestamp;
}

export interface Sessions {
  absoluteExpiresAt: Timestamp;
  createdAt: Generated<Timestamp>;
  deviceFingerprint: string | null;
  id: string;
  ip: string | null;
  lastSeenAt: Generated<Timestamp>;
  revokedAt: Timestamp | null;
  stepUpAt: Timestamp | null;
  userId: string;
  userType: string;
  vaultUnlockedAt: Timestamp | null;
}

export interface DB {
  _Migrations: _Migrations;
  admins: Admins;
  auditLog: AuditLog;
  credentialRequests: CredentialRequests;
  credentials: Credentials;
  customers: Customers;
  customerUsers: CustomerUsers;
  digestSchedules: DigestSchedules;
  documents: Documents;
  downloadTokenConsumptions: DownloadTokenConsumptions;
  emailChangeRequests: EmailChangeRequests;
  emailOtpCodes: EmailOtpCodes;
  emailOutbox: EmailOutbox;
  invoicePayments: InvoicePayments;
  invoices: Invoices;
  ndas: Ndas;
  pendingDigestItems: PendingDigestItems;
  projects: Projects;
  providerCatalogue: ProviderCatalogue;
  rateLimitBuckets: RateLimitBuckets;
  sessions: Sessions;
}
