#!/usr/bin/env node
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import * as url from 'node:url';

const SUBJECT_RE = /<%#\s*subject:\s*(.+?)\s*%>/;

export async function buildEmailTemplates({ srcDir, outFile }) {
  const layoutPath = path.join(srcDir, '_layout.ejs');
  const layoutSource = await fs.readFile(layoutPath, 'utf8');

  const localeDirs = (await fs.readdir(srcDir, { withFileTypes: true }))
    .filter((d) => d.isDirectory() && !d.name.startsWith('_'))
    .map((d) => d.name)
    .sort();

  const templates = {};

  for (const locale of localeDirs) {
    const dir = path.join(srcDir, locale);
    const files = (await fs.readdir(dir))
      .filter((f) => f.endsWith('.ejs') && !f.startsWith('_'))
      .sort();

    for (const file of files) {
      const slug = file.replace(/\.ejs$/, '');
      const source = await fs.readFile(path.join(dir, file), 'utf8');
      const m = SUBJECT_RE.exec(source);
      if (!m) {
        throw new Error(
          `Missing subject front-matter in ${locale}/${file} — first line must be "<%# subject: ... %>"`,
        );
      }
      const subject = m[1].trim();
      if (!subject) {
        throw new Error(`Empty subject in ${locale}/${file}`);
      }
      templates[slug] ??= {};
      templates[slug][locale] = { subject, source };
    }
  }

  const out =
    `// AUTOGENERATED by scripts/email-build.js — DO NOT EDIT.\n` +
    `// Re-run via "npm run build" or "node scripts/email-build.js".\n` +
    `\n` +
    `export const layoutSource = ${JSON.stringify(layoutSource)};\n` +
    `\n` +
    `export const templates = ${JSON.stringify(templates, null, 2)};\n`;

  await fs.writeFile(outFile, out, 'utf8');

  return { templates, layoutSource };
}

const isMain = (() => {
  if (!process.argv[1]) return false;
  return import.meta.url === url.pathToFileURL(process.argv[1]).href;
})();

if (isMain) {
  const here = path.dirname(url.fileURLToPath(import.meta.url));
  const srcDir = path.resolve(here, '..', 'emails');
  const outFile = path.join(srcDir, '_compiled.js');
  const { templates } = await buildEmailTemplates({ srcDir, outFile });
  const slugCount = Object.keys(templates).length;
  process.stdout.write(
    `email-build: wrote ${path.relative(process.cwd(), outFile)} (${slugCount} template${slugCount === 1 ? '' : 's'})\n`,
  );
}
